name: Setup Cloudflare Tunnel client
description: 🚛 Installs cloudflared for GitHub Actions

branding:
  icon: cloud
  color: orange

inputs:
  cloudflared-version:
    description: Specifies which version of the 'cloudflared' binary to install from the GitHub Releases page. Note that this is not your typical 'v1.2.3 'version string; instead Cloudflare uses a 'v2023.1.1' date-based versioning scheme. The default value for this field is 'latest' which will automagically default to the latest GitHub Release.
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: bash "$GITHUB_ACTION_PATH/main.sh"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_CLOUDFLARED_VERSION: ${{ inputs.cloudflared-version }}