name: Setup cloudflared
description: Setup/Install Cloudflare Tunnel client for GitHub Actions
branding:
  icon: cloud
  color: orange
inputs:
  version:
    description: cloudflared version
    default: latest
  token:
    description: GitHub token to avoid API rate limiting
    default: ${{ github.token }}
    
runs:
  using: composite
  steps:
    - name: Get cloudflared version for Unix-like
      id: version-unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/version/Unix-like.sh
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Get cloudflared version for Windows
      id: version-windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: '& $env:GITHUB_ACTION_PATH\scripts\version\Windows.ps1'
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Download cloudflared for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Unix-like.sh
      env:
        version: ${{ steps.version-unix-like.outputs.version }}
        
    - name: Download cloudflared for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\download\Windows.ps1'
      env:
        version: ${{ steps.version-windows.outputs.version }}
        
    - name: Install cloudflared on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: cloudflared