name: Setup cloudflared
description: Setup/Install Cloudflare Tunnel client for GitHub Actions
branding:
  icon: cloud
  color: orange
inputs:
  cloudflare_tunnel_credential:
    description: Cloudflare Tunnel Credential encoded in base64 (deadbeef-1234-4321-abcd-123456789abc.json)
    required: true
  cloudflare_tunnel_configuration:
    description: Cloudflare Tunnel Configuration encoded in base64 (config.yaml)
    required: true
  cloudflare_tunnel_id:
    description: Cloudflare Tunnel ID (deadbeef-1234-4321-abcd-123456789abc)
    required: true
  autostart:
    description: Autostart Cloudflare Tunnel in the background
    required: false
    default: true
    
runs:
  using: composite
  steps:
    - name: Download cloudflared for Linux
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Linux.sh
      
    - name: Install cloudflared on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: cloudflared
        
    - name: Sign in to Cloudflare Tunnel client
      shell: bash
      env:
        cloudflare_tunnel_credential: ${{ inputs.cloudflare_tunnel_credential }}
        cloudflare_tunnel_configuration: ${{ inputs.cloudflare_tunnel_configuration }}
        cloudflare_tunnel_id: ${{ inputs.cloudflare_tunnel_id }}
      run: $GITHUB_ACTION_PATH/scripts/sign-in/Unix-like.sh
      
    - name: Start Cloudflare Tunnel in the background
      if: inputs.autostart != 'false'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/autostart/Linux.sh