runs:
  using: composite
  steps:
    - if: runner.os == 'Windows'
      shell: bash
      run: pwsh "$GITHUB_ACTION_PATH/main.ps1"
    - if: runner.os != 'Windows'
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/main.sh"
