name: Shutdown cloudflared
description: Shutdown Cloudflare Tunnel autostarted by setup-cloudflared
branding:
  icon: cloud-off
  color: orange
  
runs:
  using: composite
  steps:
    - name: Shutdown cloudflared for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        kill $(< cloudflared.pid)
        if [ $RUNNER_OS = macOS ]; then lsof -p $(< cloudflared.pid) +r 1 &>/dev/null; else tail --pid=$(< cloudflared.pid) -f /dev/null; fi
        
    - name: View logs of cloudflared for Unix-like
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: cat cloudflared.log
      
    - name: Shutdown cloudflared for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: |
        Stop-Process $(Get-Content cloudflared.pid)
        Wait-Process -Id $(Get-Content cloudflared.pid)
        
    - name: View logs of cloudflared for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ runner.temp }}
      run: Get-Content cloudflared.log