inputs:
  run: {}
  url:
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: bash "$GITHUB_ACTION_PATH/main.sh"
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_RUN: ${{ inputs.run }}
