inputs:
  run: {}
  url:
    required: true

runs:
  using: composite
  steps:
    - if: runner.os == 'Windows'
      shell: bash
      run: pwsh "$GITHUB_ACTION_PATH/main.ps1"
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_RUN: ${{ inputs.run }}
    - if: runner.os != 'Windows'
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/main.sh"
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_RUN: ${{ inputs.run }}
