name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  no-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: command -V cloudflared
  runs-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: where cloudflared
  runs-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: command -V cloudflared
  pinned-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          cloudflared-version: "2023.7.3"
      - run: command -V cloudflared
      - run: cloudflared --version
  npx-serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: nohup npx -y serve &
      - run: nohup cloudflared tunnel --url http://localhost:3000 &
      - run: sleep 5m