name: Test setup-cloudflared
on:
  push:
    paths:
      - action.yml
      - scripts/**
      - .github/workflows/test.yaml
  pull_request:
    paths:
      - action.yml
      - scripts/**
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [latest, "${{ vars.SPECIFIED_VERSION }}"] # Set the SPECIFIED_VERSION variable to the last previous version in order to pass this test
        
    steps:
      - name: Setup cloudflared using setup-cloudflared
        uses: AnimMouse/setup-cloudflared@main
        with:
          version: ${{ matrix.version }}
          
      - name: Test cloudflared by checking version
        run: cloudflared -v