name: Test start & stop
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/test-start-stop.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/test-start-stop.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-start-stop:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - uses: ./start
        with:
          run: npx -y serve
          url: http://localhost:3000
      - shell: bash
        run: sleep 100
      - uses: ./stop
