name: Update tag
on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag name
        required: true
        default: v1
        
jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.event.inputs.tag-name }}